### ISSUE TITLE
Thickness variation from grain to grain

### ISSUE THREAD

**Issue by OTA-J** [mumax/3#108]
Hello,

I was wondering if it is possible to change locally the thickness of a cell. I use the ext_makegrains function to generate a grains disrtibution. My problem is simple since there is only one cell accross the film thickness. I would like to  re-define locally the size of the cells along the z-axis, meaning a way to extract all the cells indexes of a given region and then change the size of these cells along the z-axis and then repeat the process for all the regions/grains.

Many thanks in advance for your assistance !

**Comment by tupsukka** [comment]
Hello,

I've been struggling with this myself. If you follow the example in roughness.mx3, set number of cells in z-direction to 1 and add "EdegeSmooth = 8" in your script, you should see something that you are looking for. Hope this helped.

BR,
Touko

https://github.com/mumax/3/blob/a6f5e784133e98ed574f450cc9f06c62632ddc2c/test/roughness.mx3

**Comment by OTA-J** [comment]
Hello,

Thank you for your answer. Actually I did try to follow this example, but it does not give the expected results : the (output) micromagnetic parameters (anisotropy, DMI, …) are homogeneous , while I would want mumax3 to recalculate them on each region/grain, including the dipolar field. Plus, I do not really understand how the “GrainRoughness” function works : it is supposed to perform a Voronoï tessellation but the output “regions.ovf” file gives a uniform surface (only one region).
May be you understand better than me how this function works ?
Otherwise, is it possible to resize one by one the cells ? More precisely, if you choose one particular cell (if you know the cell index), can you change its size while keeping the other cells size constant ?
Many thanks in advance.

Roméo

De : tupsukka [mailto:notifications@github.com]
Envoyé : mercredi 14 juin 2017 15:11
À : mumax/3 <3@noreply.github.com>
Cc : JUGE Roméo 248290 <Romeo.JUGE@cea.fr>; Author <author@noreply.github.com>
Objet : Re: [mumax/3] Thickness variation from grain to grain (#108)


Hello,

I've been struggling with this myself. If you follow the example in roughness.mx3, set number of cells in z-direction to 1 and add "EdegeSmooth = 8" in your script, you should see something that you are looking for. Hope this helped.

BR,
Touko

https://github.com/mumax/3/blob/a6f5e784133e98ed574f450cc9f06c62632ddc2c/test/roughness.mx3

**Comment by tupsukka** [comment]
> Actually I did try to follow this example, but it does not give the expected results : the (output) micromagnetic parameters (anisotropy, DMI, …) are homogeneous , while I would want mumax3 to recalculate them on each region/grain, including the dipolar field.

So if you want to set those parameters for each regions/cell you need loop through those regions/cells and set the parameters individually like in [example 12](http://mumax.github.io/examples.html#example12). Mumax3 won't calculate the material parameters based on the thickness of the sample. 

[GrainRoughness function](https://github.com/mumax/3/blob/cd3f822a6e1d4a9865cd53d229abc3a4908d3e27/engine/shape.go#L190) returns a *Shape (Voronoi tessellation) which you have to [cut out from your geometry using boolean logic.](https://github.com/mumax/3/blob/a6f5e784133e98ed574f450cc9f06c62632ddc2c/test/roughness.mx3)

>  Plus, I do not really understand how the “GrainRoughness” function works : it is supposed to perform a Voronoï tessellation but the output “regions.ovf” file gives a uniform surface (only one region).

This is weird. Maybe your average grainsize is too big? 

Remember that origin is in the center of the sample. If you thin film is 1 nm thick, and you set zmin=0 and zmax=0.5 nm, you should get uniformly distributed surface roughness from half way of the sample to the top. Remember to set the edgesmooth to 8 if you are dealing only with 1 cell thick sample. 

BR,
Touko

**Comment by JeroenMulkers** [comment]
Mumax solves the LLG equation on a regular grid using finite differences.
Consequently, all cells have the same dimensions and it is not possible to
change the dimensions of a single cell. That being said, it is still
possible to simulate a ferromagnet with a rough surface.

The script test/roughness.mx3 shows how you can achieve a rough surface.
Let me explain this step by step with a slightly simplified script:

First we construct a simulation box with 10 layers of 1nm. Since the origin
of the reference frame is in the center of the simulation box, the bottom
of the box is at z=-5nm and the top at z=5nm

  Nx := 500
  Ny := 200
  Nz := 10
  c  := 1e-9
  setgridsize(Nx, Ny, Nz)
  setcellsize(c, c, c)

Now we will create a 'shape' which consists of the bottom half of the
simulation box and some grains between 0nm and 5nm.

  grainsize := 40e-9 // in x,y plane
  minz := 0
  maxz := 5e-9
  roughshape := grainroughness(grainsize, minz, maxz, 123)

Finally, we use the roughshape to define the geometry of the ferromagnet

  setgeom(roughshape)


Try to run test/roughness.mx3 with the GUI. At 'Display', choose quantity
'geom', and play with the Slice slider to look at the geometry of your
rough ferromagnet.

**Comment by barnex** [comment]
Thanks @JeroenMulkers. Closing as this questions is answered.
