### ISSUE TITLE
Autosave time intervals are not honored correctly

### ISSUE THREAD

**Issue by ivlis** [mumax/3#136]
I have a suspicion that mumax saves the table data and m files with incorrect time intervals.

If I run my simulation with a fixed dt as:
```
autosave(m, 1e-10)
tableautosave(1e-10)

maxdt=2e-14
mindt=2e-14
maxerr=1e-7
```

then table.txt file reads as:
```
.1000000000000526e-10	3.0298434e-06	-2.1203475e-06	0.99999905
2.100199999999625e-10	3.5836345e-06	1.3004995e-08	0.99999887
3.1000000000001537e-10	2.5944119e-06	1.6384456e-06	0.99999887
4.1000000000009774e-10	8.14388e-07	2.461114e-06	0.9999992
5.100000000000656e-10	-1.1583091e-06	2.3059092e-06	0.9999992
6.100199999998894e-10	-2.604207e-06	1.2573288e-06	0.99999905
.......
2.0100199999989475e-09	2.9922537e-06	-6.971666e-07	0.999999
2.1100199999998053e-09	2.763658e-06	7.478977e-07	0.99999887
2.210000000000663e-09	1.7194074e-06	1.8755254e-06	0.99999905
2.310000000001521e-09	4.652402e-08	2.3713767e-06	0.99999934
.....
4.710000000001746e-09	2.2163902e-06	-2.3883297e-06	0.99999887
4.810000000000536e-09	3.4924396e-06	-6.36007e-07	0.99999887
4.910019999999325e-09	3.2181845e-06	1.2051504e-06	0.99999905
5.010019999998115e-09	1.6164798e-06	2.726636e-06	0.9999992
```
For some reason the saved data points jump back and forth within the dt value at random times.

To clarify, the error may seem marginal but is some applications the time derivative is important and this noise spoils the result. Also, taking an fft of the magnetization is a widespread use case and the fft gives a wrong result if the points are not equally distributed in time.

**Comment by syockit** [comment]
While AutoSave and TableAutoSave tries to save values periodically, it does
not actually set the time points for the solver. If you need to do sampling
at precise intervals, I recommend using a loop where you run for the
specified sampling interval and saving manually after each interval.

something along the lines of:

for i:=0;i<50;i++ {
  Run(1e-10)
  TableSave()
  Save(sprint(…)) <= i don't remember the syntax
}


2017/10/19 午前8:40 "Ivan Lisenkov" <notifications@github.com>:

I have a suspicion that mumax saves the table data and m files with
incorrect spacing intervals.

If I run my simulation with fixed dt as:

autosave(m, 1e-10)
tableautosave(1e-10)

maxdt=2e-14
mindt=2e-14
maxerr=1e-7

then table.txt file reads as:

.1000000000000526e-10	3.0298434e-06	-2.1203475e-06	0.99999905
2.100199999999625e-10	3.5836345e-06	1.3004995e-08	0.99999887
3.1000000000001537e-10	2.5944119e-06	1.6384456e-06	0.99999887
4.1000000000009774e-10	8.14388e-07	2.461114e-06	0.9999992
5.100000000000656e-10	-1.1583091e-06	2.3059092e-06	0.9999992
6.100199999998894e-10	-2.604207e-06	1.2573288e-06	0.99999905
.......
2.0100199999989475e-09	2.9922537e-06	-6.971666e-07	0.999999
2.1100199999998053e-09	2.763658e-06	7.478977e-07	0.99999887
2.210000000000663e-09	1.7194074e-06	1.8755254e-06	0.99999905
2.310000000001521e-09	4.652402e-08	2.3713767e-06	0.99999934
.....
4.710000000001746e-09	2.2163902e-06	-2.3883297e-06	0.99999887
4.810000000000536e-09	3.4924396e-06	-6.36007e-07	0.99999887
4.910019999999325e-09	3.2181845e-06	1.2051504e-06	0.99999905
5.010019999998115e-09	1.6164798e-06	2.726636e-06	0.9999992

For some reason the saved data points jump back and forth within the dt
value at random times.

To clarify, the error may seem marginal but is some applications the time
derivative is important and this noise spoils the result. Also, taking an
fft of the magnetization is a widespread use case and the fft gives a wrong
result if the points are not equally distributed in time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mumax/3/issues/136>, or mute the thread

**Comment by ivlis** [comment]
Thanks, I understand your idea. Will this affect performance?

I believe that such behavior of Autosave should be at least documented because it is not evident to a user. I don't know the mumax3 internals, is it difficult to implement something like PreciseAutoSave?

**Comment by barnex** [comment]
The reason for this behaviour is twofold:

1) outputting at the precise moments would require the time step to be cut, indeed affecting performance.
2) cutting the time step would cause the end result to vary slightly, based when output is saved. This is very undesirable when troubleshooting. With previous mumax versions we have had issues where we suspected the timestep was too large. But when saving the output more frequently to investigate, the issue would disappear.

The solution by @syockit is the preferred workaround if you must have exact intervals. 
Also note that tools like mumax3-convert automatically interpolate, so you won't see any time jitter in the final analysis.

**Comment by ivlis** [comment]
@barnex Thank you for clarification.The workaround by @syockit works for me. Would you mind mentioning this behavior in AutoSave doc?
