### ISSUE TITLE
Relax() not deterministic

### ISSUE THREAD

**Issue by joh** [mumax/3#150]
In some cases, Relax() is not deterministic, i.e. repeated runs of the same script yields slightly different results. Consider the following script:

```
SetMesh(128, 128, 1, 10e-9, 10e-9, 15e-9, 0, 0, 0)

Msat  = 800e3
Aex   = 13e-12
alpha = 0.01

m = uniform(1, 1, 0)
relax()
save(m)
```

Running this 5 times in a row (on the same machine), I get different results:
```
$ md5sum standardproblem4.*.out/*.ovf
2161caf0b1af1e03132f6f7181ea708d  standardproblem4.1.out/m000000.ovf
2161caf0b1af1e03132f6f7181ea708d  standardproblem4.2.out/m000000.ovf
3445f9e1b2cda5376ad09084d2261f70  standardproblem4.3.out/m000000.ovf
2161caf0b1af1e03132f6f7181ea708d  standardproblem4.4.out/m000000.ovf
3445f9e1b2cda5376ad09084d2261f70  standardproblem4.5.out/m000000.ovf
```
... even though the scripts are identical:
```
$ md5sum standardproblem4.*.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.1.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.2.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.3.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.4.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.5.mx3
```

Is this to be expected? If so, why? 

From my preliminary investigation the behavior seems to depend on the initial condition, e.g. setting `m = uniform(1, .1, 0)` produces the same result every time. Also, ```Run()``` is not affected and produces the same result every time.

**Comment by godsic** [comment]
The path Relax() takes is strongly affected by numerical rounding
noise. So it is quite likely to end up in a slightly different states,
unless it is of some high symmetry.
  

-----Original Message-----

Date: Mon, 15 Jan 2018 14:49:42 +0000 (UTC)
Subject: [mumax/3] Relax() not deterministic (#150)
Cc: Subscribed <subscribed@noreply.github.com>
To: mumax/3 <3@noreply.github.com>
Reply-to: mumax/3 <reply+0023b1db200381ab3b8f49a98cecb071e62a58a9b400e3
9092cf000000011674818592a169ce1133fa08@reply.github.com>
From: Johannes H. Jensen <notifications@github.com>
In some cases, Relax() is not deterministic, i.e. repeated runs of the
same script yields slightly different results. Consider the following
script:

SetMesh(128, 128, 1, 10e-9, 10e-9, 15e-9, 0, 0, 0)

Msat  = 800e3
Aex   = 13e-12
alpha = 0.01

m = uniform(1, 1, 0)
relax()
save(m)

Running this 5 times in a row (on the same machine), I get different
results:

$ md5sum standardproblem4.*.out/*.ovf
2161caf0b1af1e03132f6f7181ea708d  standardproblem4.1.out/m000000.ovf
2161caf0b1af1e03132f6f7181ea708d  standardproblem4.2.out/m000000.ovf
3445f9e1b2cda5376ad09084d2261f70  standardproblem4.3.out/m000000.ovf
2161caf0b1af1e03132f6f7181ea708d  standardproblem4.4.out/m000000.ovf
3445f9e1b2cda5376ad09084d2261f70  standardproblem4.5.out/m000000.ovf

... even though the scripts are identical:

$ md5sum standardproblem4.*.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.1.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.2.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.3.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.4.mx3
fdd12c27ea1903a3a7d57947aa68fd87  standardproblem4.5.mx3

Is this to be expected? If so, why?

From my preliminary investigation the behavior seems to depend on the
initial condition, e.g. setting m = uniform(1, .1, 0) produces the same
result every time. Also, Run() is not affected and produces the same
result every time.


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.



  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/mumax/3","tit
le":"mumax/3","subtitle":"GitHub repository","main_image_url":"https://
cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-
95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in GitHub","url":"https://gith
ub.com/mumax/3"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message
":"Relax() not deterministic (#150)"}],"action":{"name":"View
Issue","url":"https://github.com/mumax/3/issues/150"}}}
-Mykola

**Comment by joh** [comment]
Ok, but shouldn't the numerical rounding noise be the same across runs on the same system?

**Comment by barnex** [comment]
@joh: this question has been asked many times before. Surprisingly, on a GPU architecture, some reduction operations are not completely deterministic. E.g.: a+b+c might sometimes be calculated as (a+b)+c and sometimes as a+(b+c), depending on scheduling details. Hence a tiny non-deterministic truncation error occurs.

**Comment by joh** [comment]
@barnex Ah, thank you for the explanation. Maybe something that should be added to the documentation?
