### ISSUE TITLE
Installation of mumax on centos7

### ISSUE THREAD

**Issue by pavankulka** [mumax/3#247]
Is there any documentation/guide to install mumax on CentOS7? In my environment I don't have internet access to nodes so it would be helpful if I can get the rpm package of the mumax software

**Comment by JeroenMulkers** [comment]
We are not planning to make packages for every linux distribution. If the linux mumax3 binary does not work for you, try to build mumax3 from the source.

The instructions on how to build mumax3 on ubuntu can be found in the README. I presume that the build process is very similar on other linux distributions. Instead of using apt-get, use the package manager of your system to install the dependencies.
