### ISSUE TITLE
No binary for GPU. Your nvidia driver may be out-of-date

### ISSUE THREAD

**Issue by zkhodzhaev** [mumax/3#278]
I have (MuMax3, Windows, NVIDIA Drive >451.21), 
The computer Nvidia:
![image](https://user-images.githubusercontent.com/21960382/104082212-f855a100-51f9-11eb-8492-dc47d7db7fe6.png)

The Error: "No binary for GPU. Your nvidia driver may be out-of-date"

**Comment by JeroenMulkers** [comment]
Does [this build](https://mumax.ugent.be/mumax3-binaries/mumax3.10_windows_cuda10.2.zip) work on your system?

**Comment by zkhodzhaev** [comment]
> Does [this build](https://mumax.ugent.be/mumax3-binaries/mumax3.10_windows_cuda10.2.zip) work on your system?

I'll try now.

**Comment by zkhodzhaev** [comment]
> Does [this build](https://mumax.ugent.be/mumax3-binaries/mumax3.10_windows_cuda10.2.zip) work on your system?

It does :) can you tell me why this version works?

**Comment by JeroenMulkers** [comment]
My apologies for the late answer.

mumax3 is compiled against different CUDA versions. The mumax3 build which you need to download depends on both the gpu architecture and the gpu driver. In most cases it is sufficient to know which driver you are using. That is why there is only a selector for the driver version when you want to download a mumax3 build.

Older GPUs (e.g: Geforce GTX 690) are not supported by CUDA11. In this case, you have to use a mumax3 executable which is build against an older CUDA version, even when you are using the most recent driver.

I reopened this issue because I want to update the download page to resolve this kind of confusion about the mumax3 builds in the future.

**Comment by zkhodzhaev** [comment]
Thank you.
