### ISSUE TITLE
set the regions' m of a cylinder ，but table.text can not show the correct  setting of m

### ISSUE THREAD

**Issue by xzcwchen** [mumax/3#305]
I am a new guy of mumax3, when i set the some layers ' cylinder , each layer has itself m, then run it,  the table.txt can not show mysetting about the m of different layers , could you help me ?  
SetGridsize (25,25,5)
SetCellsize(2e-9,2e-9,0.4e-9)
top:=cylinder(50e-9,0.8e-9).transl(0,0,0.6e-9)
bottom:=cylinder(50e-9,1.2e-9).transl(0,0,-0.4e-9)
setgeom(top.add(bottom))
save(geom)
defRegion(0, bottom)
defRegion(1, top)
save(regions)
Ku1.setregion(0, 1.2e6)
Ku1.setregion(1, 1.2e6)
Msat.setregion(0,1.26e6)
Msat.setregion(1,1.26e6)
Aex.setregion(0, 3e-11)
Aex.setregion(1, 3e-11)
anisU.setRegion(0,vector(0,0,1))
anisU.setRegion(1,vector(0,0,1))
RKKY :=-2    // 1mJ/m2
scale :=(RKKY*0.4e-9)/(2*Aex.average())
ext_scaleExchange(0,1,scale)
print(scale)
alpha=0.01
m.setregion(0,uniform(0,0,1))
m.setregion(1,uniform(0,0,1))
tableadd(m.region(0))
tableadd(m.region(1))
tableautosave(0.01e-9)
autosave(m,0.01e-9)
run(5e-9)

the table.text  can't show the correct m.region0

**Comment by JonathanMaes** [comment]
When I run this script, the output is as expected. My result for `table.txt`:

|# t (s)               |mx ()          |my ()         |mz ()     |m.region0x () |m.region0y ()  |m.region0z ()|m.region1x ()  |m.region1y ()  |m.region1z ()|
|----------------------|---------------|--------------|----------|--------------|---------------|-------------|---------------|---------------|-------------|
|0                     |0              |0             |1         |0             |0              |0.683279     |0              |0              |1            |
|1.0006024086180722e-11|-7.961596e-06  |7.6460106e-05 |0.2000324 |0.000370543   |0.0045818593   |0.6831731    |-0.0008333557  |-0.00986739    |-0.9996866   |
|2.0003445930919624e-11|-5.3845088e-05 |-0.0001065214 |0.19999956|-0.00017507494|-0.00037021775 |0.683278     |0.00024972868  |0.0005464342   |-0.99999905  |
|...|...|...|...|...|...|...|...|...|...|
|4.980005302187858e-09 |-6.938496e-10  |1.7802736e-10 |0.2       |-2.3838707e-09|5.8137173e-10  |0.683279     |3.4985899e-09  |-8.3181007e-10 |-1           |
|4.990001240787798e-09 |-6.615914e-10  |1.0570225e-10 |0.2       |-2.2542659e-09|3.882318e-10   |0.683279     |3.294863e-09   |-5.8683797e-10 |-1           |
|5e-09                 |-7.1470435e-10 |1.6993304e-10 |0.2       |-2.436534e-09 |5.645628e-10   |0.683279     |3.5622136e-09  |-8.1621665e-10 |-1           |

I suppose what you mean by this issue is that you get an $m_z < 1$ in region 0. This is because region 0 is the default region and therefore includes the empty space around the cylinder.
