### ISSUE TITLE
defregion?

### ISSUE THREAD

**Issue by Chris317** [mumax/3#319]
The default region can only set 256 different regions. What should I do if I want to set 300 different Msats?

**Comment by MathieuMoalic** [comment]
It's not possible with the current mumax binaries. You can modify the source code and recompile mumax. It will probably come at a performance cost but it might not be noticeable. Anyway, if you can find a work around, you should

**Comment by jplauzie** [comment]
Hello,

As Mathieu mentioned, there is a limit of 256. If you need more, you will to modify the source code and recompile. You can see an existing topic on the subject here:

https://github.com/mumax/3/issues/124#issue-255113504

It is not too difficult, basically ones needs to change the regions variable from 8-bit type (uint8_t) to something larger (note this will come with a memory penalty which scales as NREGIONS squared). 

Instead, I would also recommend trying to find a workaround. Often you can use less regions with some clever tricks without greatly affecting the result. For example, instead of picking 300 separate Msats, have them randomly pick from a distribution of 30 (or 250) or so. Any regions that happen to have the same value can reuse the same region parameter value.

Best,
Josh L.

**Comment by 1eevy** [comment]
> Hello,
> 
> As Mathieu mentioned, there is a limit of 256. If you need more, you will to modify the source code and recompile. You can see an existing topic on the subject here:
> 
> [#124 (comment)](https://github.com/mumax/3/issues/124#issue-255113504)
> 
> It is not too difficult, basically ones needs to change the regions variable from 8-bit type (bytes in Go, uint8_t in Cuda) to something larger (note this will come with a memory penalty which scales as NREGIONS squared).
> 
> Instead, I would also recommend trying to find a workaround. Often you can use less regions with some clever tricks without greatly affecting the result. For example, instead of picking 300 separate Msats, have them randomly pick from a distribution of 30 (or 250) or so. Any regions that happen to have the same value can reuse the same region parameter value.
> 
> Best, Josh L.

Thanks for this guide! I want to change the limit too. I have tried to chage the 8-bit type (bytes in Go, uint8_t in Cuda) to 16-bit, but it didnot work, maybe I did not change all the regions variable that should be changed. So, can you please help to point out which files should be changed? Thanks again.

**Comment by JonathanMaes** [comment]
Due to the prohibitive performance impact associated with increasing the number of regions, mumax³ will stick to supporting a maximum of 256.
