### ISSUE TITLE
(Minor) Inconsistent behavior between m_full and m_full.Comp() when setgeom is used

### ISSUE THREAD

**Issue by jplauzie** [mumax/3#322]
Hi,

There seems to be a slight difference between the averaging method used to calculate the components of m_full vs m_full.Comp(). It seems the first averages over the entire universe, even after setgeom is called. Whereas the second respects the geometry, and averages over the geometry. A simple test script:

SetGridsize(100, 100, 1)
SetCellsize(1e-9, 1e-9, 1e-9)

m=uniform(0,0,0)

setgeom( rect(50e-9,100e-9))
defregion(1,rect (50e-9,100e-9))
msat.setregion(1,500e3)
m.setregion(1,uniform(1,0,0))

print(m_full)
print(m_full.Comp(0))

yields output: 250000 0 0 and 500000 respectively.

If one doesn't use setgeom (for instance, instead defining the rectangular portion by using regions), they both yield 250000 as expected. An example being:

SetGridsize(100, 100, 1)
SetCellsize(1e-9, 1e-9, 1e-9)

m=uniform(0,0,0)

defregion(1,rect (50e-9,100e-9))
msat.setregion(1,500e3)
m.setregion(1,uniform(1,0,0))

print(m_full)
print(m_full.Comp(0))

yields output: 250000 0 0 and 250000 respectively. Which makes sense, the geometry and the universe are the same since setgeom wasn't called.

![mfullbug](https://user-images.githubusercontent.com/108704520/216745993-9ba4d4b8-d548-452c-b58b-19c5f64ecaac.jpg)

Best,
Josh Lauzier

**Comment by JonathanMaes** [comment]
It seems that, for an output quantity `foo`,
- `print(foo.Comp(i))` always averages over the **geometry**.
- `print(foo)` just prints `foo.Average()[0] foo.Average()[1] foo.Average()[2]`, but<br>`foo.Average()` averages over
  - the **geometry** if `foo` is the magnetization `m`.
  - the **universe** if `foo` is any other output quantity.

Therefore, all quantities except `m` will exhibit the reported discrepancy, e.g. `B_demag`:
```go
print(m)                //1 0 0
print(m.Average()[0])   //1
print(m.Comp(0))        //1

print(B_demag)                //-0.00021174240112304687 2.4237670004367828e-11 0
print(B_demag.Average()[0])   //-0.00021174240112304687
print(B_demag.Comp(0))        //-0.02063170591990153
```

#### What to do now?
- We could just keep it as it is now. Besides maintaining backwards compatibility, the current implementation allows the user to access both the universe-average `foo.Average()[i]` and the geometry-average `foo.Comp(i)` (except for `m`, where both are the same), which can be useful.<br>However, this is not obvious behavior at all and should be documented more clearly.
- We could get rid of the discrepancy by making `.Comp()` use the same averaging method as `.Average()`.<br>However, such a change would not be backwards compatible.<br>(Note to self: to do this, add `func (q *component) average() []float64 {return AverageOf(q.parent)[q.comp:q.comp+1]}` to `comp.go`)

<details>
<summary>Click to show "under the hood" details (note to self) </summary>

`.Comp()` simply returns a `ScalarField`, which does not track what physical quantity it represents. Therefore, any call of `.Comp()` will end up using the same averaging method, which in this case is `sAverageMagnet()` (instead of `sAverageUniverse()`) because this makes most sense for `m`.

All vector quantities except `m` (e.g. `m_full`, `B_demag`...) are stored as a `fieldFunc`, whose `.average()` uses `qAverageUniverse()`, which probably makes sense for fields extending beyond the magnet. `m.Average()` is the only custom implementation of `.Average()`, using `sAverageMagnet()` instead, which makes sense because one would expect the average magnetization to be taken over the magnet only.

</details>

**Comment by JonathanMaes** [comment]
As seen in the commit above, we have decided to preserve backwards compatibility by just adding a note to the documentation for output quantities.
