### ISSUE TITLE
save m with ovf document while running "relax" order 

### ISSUE THREAD

**Issue by bananaacat** [mumax/3#327]
I tried to look at how the magnetic domains act while doing the "relax" order using mumaxview, but I found that I can't save any ovf document either with "save" or "autosave", I wonder if it is because I set the period improperly , or because I used the wrong order or other possiblities,Thank you so much.

**Comment by JonathanMaes** [comment]
Output can not be saved during the operation of `relax()`. In essence, `relax()` solves the LLG equation with precession disabled until the torque becomes sufficiently small.
A similar effect could be achieved by setting `DoPrecess` to false and then calling `run()`. Because `run()` advances through time, output can be saved at set intervals with this method.
