### ISSUE TITLE
❗ mumax mailing list is banned

### ISSUE THREAD

**Issue by AbsoluteVacuum** [mumax/3#330]
1. Is there any possibility to extract the information which was posted there before the spam wave?
2. There should be some place to exchange information, ask questions and share knowledge on mumax. What are the possible options for such place? 

As for the 2, it should be accessible to read for non-registered users, and the information should not be lost (like what happened with the mailing list ban). IMHO some securely hosted forum would be the best option.

**Comment by AbsoluteVacuum** [comment]
It seems that the mailing list can be reinstated. Below is a copypaste from a 2-year-old answer from Google:

> Banned group appeals process If you’re the owner of a group with banned content, you can appeal the decision.
> 
>     Review your group’s content, and remove any content that might be offensive.
>     Update your group’s security settings. When you use settings like [message moderation](https://support.google.com/groups/answer/2627595), you can make it harder for group members to post spam or adult content, and make it easier to keep your community healthy and active.
>     Open [Google Groups](http://groups.google.com/) > click My Groups > name of the group you want to edit.
>     Click the name of your group > Request Review on the group’s home page.

If the mailing list is reinstated, moderation policy must be tightened to ensure that the group is not banned again.

**Comment by jplauzie** [comment]
I don't think there is a way to extract what was in there, other than piecemeal from something like the Internet Archive, perhaps. I do have emails from the group going back to ~2022, but not prior to that. From a similar Google help page, there is a "continue anyway" option to access a banned group, but it seems to be only available to the group owner. 

However, I think it should be able to be reinstated, as you've found. I've sent Jonathan an email, if it doesn't get a response I'll CC a few more people from the mumax group. Going forward, probably there will need to be someone(s) more active that is able to remove spam proactively, if the group wants to stick with the google group. It was quite a lot, over 100 posts in a day, it would've really hurt the usability regardless of the ban. I'd be inclined to want to stick with the google group, because there is quite a lot of archived little details that cannot be found anywhere else.

**Comment by JLeliaert** [comment]
I performed the following measures, hoping to revive the mailing list:

- I've deleted all spam messages from the days before the ban
- I've asked for a review to unban the mailing list
- I've banned the bad actors from the spam wave
- I've made posting restrictions more strict, requiring moderation for new users

**Comment by JLeliaert** [comment]
Closed because the list is functional again.
