### ISSUE TITLE
Change parameters of Mumax3 script in command prompt

### ISSUE THREAD

**Issue by Lee-89757** [mumax/3#336]
Hi,

Is it possible to change the parameters of Mumax3 script directly in command prompt? For exampe, if I wan to change the value of "Ms" or "Ku" in my txt file for the mumax simulation, can I do it in the command prompt? 

I searched the functions of Mumax3 and didn't find the function like "-parameter" to realize this. Have anyone thried this before?
![Picture1](https://github.com/user-attachments/assets/7e2a7f16-20db-4fdf-be43-da94f82bb86a)

**Comment by JonathanMaes** [comment]
Instead of using a command line parameter, you can adjust the parameter automatically by running the mumax³ script in another programming language. By storing the input script code as a string, string formatting can be leveraged to change variables as desired when running the script multiple times. See the [mumax³ workshop notebook](https://colab.research.google.com/github/JeroenMulkers/mumax3-tutorial/blob/master/postprocessing.ipynb#scrollTo=wKe6laCH0s7F&line=1&uniqifier=1), where this is done using Python with the `run_mumax3(script, name)` function.

Note that the active [mumax mailing list](https://groups.google.com/g/mumax2) can be used to ask questions related to the usage of mumax³.

**Comment by Lee-89757** [comment]
Hi Jonathan,

Thank you very much for your reply! I'll try to use Python to write the script and I've followed the goole group of mumax. If I have further questions, I'll ask in the group.

Best wishes
Lee
