### ISSUE TITLE
[go1.6] panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by godsic** [mumax/3#59]
@barnex  as of go 1.6 "Briefly, Go and C may share memory allocated by Go when a pointer to that memory is passed to C as part of a cgo call, provided that the memory itself contains no pointers to Go-allocated memory, and provided that C does not retain the pointer after the call returns." 

Not really sure why mumax is affected, but it now needs some love) 

Forcing GODEBUG=cgocheck=0 does not show any further incompatibilities.

**Comment by barnex** [comment]
The problem was that the cuda driver api takes kernel arguments as an array of pointers to the argument values. This was the go-pointer-to-go-pointer issue. To make matters more complicated, the pointer check is conservative and treats a pointer into a struct as passing the entire struct. Finally, non-pointer values stored inside an unsafe.Pointer occasionally cause a "fatal error: bad pointer in write barrier". 

Fix is rather ugly:
d0824a59379fa5213aaac0013ced78659287a2ad
08170d9358b7c380a21ae51744e6509df1dac001
c1ee4e13c2019ef67f3e0feeefbc651d88020198
