### ISSUE TITLE
Cuda 7.0 deprecated completely?

### ISSUE THREAD

**Issue by ivlis** [mumax/3#64]
The 3.9.1c release does not have a binary linked with cuda 7.0 libraries.

**Comment by barnex** [comment]
cuda 7 is far from deprecated. On the contrary, when this binary was built, cuda 7.0 was in my opinion not mature enough to use with mumax. I see they have some cuFFT patches out now, so I expect you should be able to build for cuda 7 now.

**Comment by godsic** [comment]
I would suggest (based on my private communication with Nvidia) to 
avoid CUDA7 due to the cufft synchronization bug. They did release a 
patch later on, but that one was not even mentioned on the official 
CUDA7 download page. So most likely majority of CUDA7 are still 
affected by the bug.

-Mykola
