### ISSUE TITLE
Radial Anisotropy

### ISSUE THREAD

**Issue by LLizardi** [mumax/3#69]
I wanna know, if there're a function to have a radial anisotropy, for example for  a cylinder geometry

Thanks :)

**Comment by LLizardi** [comment]
??? :(

**Comment by kahlos** [comment]
You could probably do something like this using regions. I've run a simulation where I define different parameters for 255 circular regions. The key part is as follows:

```
for i:=1; i<256; i++{
  DefRegion(i, circle(i*samplesize/255).sub(circle((i-1)*samplesize/255)))
  Temp.SetRegion(i, (Tmin + (256-i)*(Tmax - Tmin)/255))
}
```

This splits the _samplesize_ into 255 equal sized regions, then starting from the middle, defines a set of rings _circle().sub(circle())_ and assigns a different value of parameter _Temp_ to each ring.

Otherwise, this is something you'd likely have to add to mumax yourself.

**Comment by barnex** [comment]
Thanks @kahlos . Closing.
