### ISSUE TITLE
Feature: Web client, parameter upload file

### ISSUE THREAD

**Issue by davekall** [mumax/3#70]
Hello,

We are currently dealing with some crashes, and hard quits for the client and server. Would it be possible to have an "parameter file" that one could **upload** or **export** that would set all the parameters in the web client, this way using the web client could be more user friendly.

Would this be hard to add? Because I could take a look at it.

Thanks

**Comment by barnex** [comment]
Hey Dave,
could you perhaps post a stack trace of the crash you mention? I would like to fix the root cause first before adding functionality on top.

I'm not exactly sure what you mean by 'parameter file'. How would this be different from the input files that mumax3 already has? 

Also, by "web client" do you mean the mumax3 web UI or mumax3-server's web UI?

Cheers,
-Arne;

**Comment by davekall** [comment]
Hi Arne,

Sorry, I was talking with someone in my lab about an issue they were having
with recently. I would say it would be the same for an input file, just on
the mumax3 web-UI for the parameters a user can enter. I believe we are
using Mumax 3.9.

When the program crashed, we believe it was calculating the periodic
boundary conditions, and crashed in the demag kernel. However, checking
today it seemed to be fine if the system size was not a power of 2.


Looking around we don't see a stack trace file. Also when it hard crashed,
nothing was generated. Could be an issue on our side.

On Thu, Jul 7, 2016 at 4:37 PM, Arne Vansteenkiste <notifications@github.com

**Comment by barnex** [comment]
OK, so it sounds the crash you mention is probably just a checkfail when you attempt to use an unsupported number of cells with PCB (needs to even, as stderr should mention).

I still don't fully understand your feature request. Do you mean you would like to start "mumax3 -i", and then provide the input file through the web UI instead of through the command line? A bit like pasting the input into the command box, but with an "upload" button?

Also, exporting all parameters is not as trivial is it sounds, as they may be space- and time-dependent. You may write an input file, however, that prints or saves all the parameters at a given point in time. You might even print something like "alpha=...", so that you can load that output to restore the parameters. However the general case is not so simple, as parameters may be a time-dependent expression, etc.

**Comment by davekall** [comment]
Yes provide a input file through the web UI as an upload button that just
controls the parameters available on the web UI, from all of the text boxes
and sliders, such as "mesh", "geometry", "initial_m", "solver", "display"
and "parameters".

Yes I see the difficulty as you describe. What I had in mind was a snapshot
of what the web interface setting were, from all the text boxes and
sliders, as described above.

**Comment by barnex** [comment]
OK, I think I understand your request now. Actually most of that functionality that is already there, albeit not exactly in the form you describe:

  * To upload an input file through the web UI: there is already the possibility to paste input in the command box. You can separate statements with semicolons instead of newlines, if you want.

  * For every click you make in the web UI, the history shows the corresponding command that has the same effect. Hence, after clicking around you can copy paste the corresponding command history to replay your clicks and restore all parameter values.

  * Clicks in the we UI that do not change the simulation state (e.g. zooming in on the magnetization view) are not reflected in the command history. I prefer not to make those replay-able. Doing so would tightly couple the web UI and input script, making it hard or impossible to change the UI without breaking the input script specs. Remember that we promise backwards compatibility.

I realize this is not entirely what you asked for, but probably covers say 90% of your use case.

I would be happy though to review a pull request for the script upload button so that you don't need to copy-paste the input.

**Comment by davekall** [comment]
Hm, good point. If 90% of that is already there, then for the 10% gain
isn't as important. I will relay this information on to our lab. As I said
previously it was more for quick testing, and copying and pasting is a
sufficient solution. If I get time to look at this I could send you pull
request.

Thanks again for mulling this over with me!
