### ISSUE TITLE
minimizer should be moved to a branch

### ISSUE THREAD

**Issue by syockit** [mumax/3#90]
I was the author of the minimizer code, but alas I no longer own a CUDA machine, and can no longer do any maintenance work.

If upstream does not have anyone dedicated to maintain it, I propose moving it to a branch.

- There were times when minimizer is buggy; sometimes the stepper move into a rubbish, invalid magnetic state.
- The solver could be introduced to list of available solvers in SetSolver, to allow people finer controls or make the intermediate steps visible.
- Sometimes I wonder if single floating point doesn't have enough accuracy for the algorithm to work robustly.

**Comment by barnex** [comment]
For the moment mumax provides Relax() and Minimize(). The documentation states that Relax is slow but certain, while Minimize is fast but does not always guarantee convergence. Since Minimize is now part of the API, we can't just remove it without breaking existing scripts. So if anyone would be willing to take up maintenance of this part of the code, that would be great.
Thanks,
-Arne;

**Comment by barnex** [comment]
Closing as we cannot remove Minimize() and the documentation states that Relax() is the robust choice.
